#!/bin/bash

echo -e "Name of the script is:\t $0 \n"

echo -e "First Arguement is: \t $1 \n"

num1=$1

if [ $num1 -gt 10 ]; then
	echo "Number is greater tham 10"
else
	echo "Number is less than 10"
fi
