#!/bin/bash

echo -e "Usage:\t $0 <value> \n"

if [ $# -eq 0 ]; then
	echo -e "we need a value...Sir.... \n"
	read -p "Please enter a number:		" range
#	[ $? -eq 0 ] && echo -e "\n You should have entered a number... f u... \n" && exit 1
	if [[ -z "$range" || ! "$range" =~ ^[0-9]+$ ]]; then
		echo -e "\n you should have enter a number... bye bye.. \n"
		exit 1
	fi
else
	range=$1
fi

#range=$1

echo -e "\n USer Report As Follows :\n"
awk -v limit=$range -F: '
BEGIN {printf "%-15s %-8s %s \n","UserName","UID","SHELL"}
$3 > limit {printf "%-15s %-8s %s \n", $1, $3, $7, count++}
END {printf "\t Number of users with UID %d is %d\t\n",limit,count}
' /etc/passwd



#Here, we are using awk variable
# -v limit=$range will assign value of range to limit
# count+= we have used, cause no need to initialize in awk, it starts from "0" only, no garbage value concept here
#this printf is similar to something we used in C language
